repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.11.5
     hooks:
        - id: ruff  # Linter
          args: [--fix]  # Ensure fixes are applied
        - id: ruff-format  # Formatter

   - repo: https://github.com/yunojuno/pre-commit-xenon
     rev: v0.1  # Use the latest stable version
     hooks:
       - id: xenon
         args: ["--max-absolute", "A", "--max-modules", "A", "--max-average", "A"]